name: Build Scrcpy Mobile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Xcode
      run: sudo xcode-select -s '/Applications/Xcode.app/Contents/Developer'

    - name: Install dependencies
      run: |
        brew install glfw
        brew install libavformat
        brew install sdl2

    - name: Compile Scrcpy Mobile
      run: make